# Generated by Django 2.2 on 2019-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('start', models.BigIntegerField()),
                ('finish', models.BigIntegerField()),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
    ]
